/*
Steven Gaona STE2342585
Date: 4/14/25
*/

// here i set my dom variables using the document object
const inStateSelection = document.getElementById('in-state');
const outStateSelection = document.getElementById('out-state');
const zipInput = document.getElementById('zip-input');
const zipButton = document.getElementById('zip-submit');

function calculateTuition(tuition) {
    // this function takes the user selection and multiplies it by in state or out of state tuition cost. it stores the selection as a variable and converts it to an integer. it then calculates the total. it then targets the span element and updates the text with the total amount that is convereted to a formatted string that includes commas for thousands place using toLocaleString()
    if (tuition == 5000) {
        let semesters = parseInt(inStateSelection.value);
        semesters = semesters * tuition;
        document.getElementById('in-state-total').innerText = `$${semesters.toLocaleString()}`;
    } else if (tuition == 10000) {
        let semesters = parseInt(outStateSelection.value);
        semesters = semesters * tuition;
        document.getElementById('out-state-total').innerText = `$${semesters.toLocaleString()}`;
    }
}

// this code attaches the event listeners to the semester selections and invokes the in state or out of state tuition cost and updates the total to the user on the screen. 
inStateSelection.addEventListener('change', () => {
    calculateTuition(5000);
});
outStateSelection.addEventListener('change', () => {
    calculateTuition(10000);
});



function calculateRate() {
    // this function uses a regular expression (regex generated by chatgpt) to evaluate the input. if the zip code is valid, the function will then check to see if the zip code begins with an 8. if it begins with an 8 then a message is displayed, if not a separate message is displayed.
    let zipRegEx = /^\d{5}$/;

    if (zipRegEx.test(zipInput.value)) {
        if (zipInput.value.startsWith("8")) {
            document.querySelector('.congrats').style.display = "block";
            document.querySelector('.no-congrats').style.display = "none";
        } else {
            document.querySelector('.congrats').style.display = "none";
            document.querySelector('.no-congrats').style.display = "block";
        }
    } 
};

// here i attached an event listener and called the calculateRate function.
zipButton.addEventListener('click', calculateRate);
